### ISSUE TITLE
methods assume internal structure that might not be available

### ISSUE THREAD

**Issue by Morriz** [OvidijusParsiunas/deep-chat#306]
Hi, I get the following error when the history is set to `[]` and subsequently (after a `loadSession` event) we run `clearMessages()`, then we get the following error:
```
Error: TypeError: Cannot read properties of undefined (reading 'innerContainer')
    at t.hideRoleElements (deepChat.bundle.js:1:22554)
    at Wi.addInnerContainerElements (deepChat.bundle.js:1:79629)
    at Wi.createMessageElements (deepChat.bundle.js:1:79057)
    at Wi.createNewMessageElement (deepChat.bundle.js:1:78745)
    at Wi.createAndAppendNewMessageElement (deepChat.bundle.js:1:78069)
    at Wi.addIntroductoryMessage (deepChat.bundle.js:1:194035)
    at Wi.clearMessages (deepChat.bundle.js:1:198408)
    at index.html:209:36
```

**Comment by OvidijusParsiunas** [comment]
Hi @Morriz.
I have been trying to reproduce the error but can't seem to trigger it.

There is a chance that the `dev` version of Deep Chat may have fixed your issue. Could you try either `deep-chat-dev` or `deep-chat-react-dev` packages version `9.0.204` to see if they fix the issue for you. These packages are used exactly the same as the core ones except their names are different.

If the issue is still occurring, could you share some more details of the configuration you are using for Deep Chat or how you are using it.

Thankyou!

**Comment by Morriz** [comment]
Tnx again for long reply. I have stopped using `chatElementRef.clearMessages` in my scenario and used `chatElementRef.history = []` instead, which helped :)
